volumes:
  peer0.org4.hl7-fhir.com:

networks:
  test:
    name: fabric_test

services:

  couchdb3:
    container_name: couchdb3
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "11084:5984"
    networks:
      - test

  peer0.org4.hl7-fhir.com:
    container_name: peer0.org4.hl7-fhir.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org4.hl7-fhir.com
      - CORE_PEER_ADDRESS=peer0.org4.hl7-fhir.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.hl7-fhir.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.hl7-fhir.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.hl7-fhir.com:13051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:21051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/org4.hl7-fhir.com/peers/peer0.org4.hl7-fhir.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org4.hl7-fhir.com/peers/peer0.org4.hl7-fhir.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.hl7-fhir.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 13051:13051
      - 21051:21051
    networks:
      - test
    depends_on:
      - couchdb3