version: '3'

services:
  api:
    container_name: api
    image: springboot-hapifhir
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      - FABRIC_CONNECTION=/app/organizations/peerOrganizations/org2.hl7-fhir.com/connection-org2.json
      - FABRIC_WALLETPATH=/app/organizations/peerOrganizations/org2.hl7-fhir.com/users
    volumes:
      - ./../../organizations:/app/organizations

      #docker-compose up --build